# create service from dockerfile
version: '3.9'

services:
  # postgres service
  db:
    image: postgres:latest
    # volumes:
    #   - pos_db_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  api:
    # django service
    build: .
    image: auto-shop:latest
    command: ./script/entrypoint.sh
    working_dir: /app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      ENGINE: postgres
      POSTGRES_NAME: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DJANGO_SETTINGS_MODULE: config.settings.development
      CORE_LOG_LEVEL: DEBUG