# Generated by Django 4.2.6 on 2023-10-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="trx_category",
            field=models.ManyToManyField(
                blank=True,
                related_name="trx_categories",
                to="ledger.trxcategory",
                verbose_name="Transaction Category",
            ),
        ),
    ]
