# Generated by Django 4.2.6 on 2023-10-14 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="trx_category",
        ),
        migrations.AddField(
            model_name="transaction",
            name="trx_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trx_categories",
                to="ledger.trxcategory",
                verbose_name="Transaction Category",
            ),
        ),
    ]
