# Generated by Django 4.2.6 on 2023-10-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ledger", "0002_remove_transaction_trx_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=15, verbose_name="Amount"
            ),
        ),
    ]
